### ISSUE TITLE
Add DoneButtonTapped action to Start/Time Time Entry Module

### ISSUE THREAD

**Issue by semanticer** [toggl/android#119] opened 2020-04-02 10:37 UTC
## Description
Add DoneButtonTapped action to Start/Time Time Entry Module. 
## Dependencies
#112 
## Definition of done
- [ ] Action is added
- [ ] The reducer closes expanded layout and saves changes made to TE
- [ ] Tests are added

**Comment by heytherewill** [comment] 2020-04-07 13:53
Duplicate of #60

**Closed** 2020-04-07 13:54 UTC
Labels: size-S
